# Makefile generated by Metrowerks CodeWarrior IDE
#

all: HLServer(M-Classic) HLServer(MD-Classic) HLServer(WD) HLServer(W) Debug Final Build_All HLServer(M-Carbon) HLServer(MD-Carbon) repo

clean: clean_HLServer(M-Classic) clean_HLServer(MD-Classic) clean_HLServer(WD) clean_HLServer(W) clean_Debug clean_Final clean_Build_All clean_HLServer(M-Carbon) clean_HLServer(MD-Carbon) clean_repo

